-- 코드를 입력하세요
SELECT  DISTINCT A.USER_ID, A.PRODUCT_ID
FROM ONLINE_SALE A INNER JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID AND A.PRODUCT_ID = B.PRODUCT_ID AND A.ONLINE_SALE_ID != B.ONLINE_SALE_ID
ORDER BY A.USER_ID, PRODUCT_ID DESC