select DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where DATE_FORMAT(SALES_DATE, "%Y%m") = "202203"
union
select DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
from OFFLINE_SALE
where DATE_FORMAT(SALES_DATE, "%Y%m") = "202203"
order by SALES_DATE, PRODUCT_ID, USER_ID;

# select DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE, PRODUCT_ID, "NULL" USER_ID, SALES_AMOUNT
# from OFFLINE_SALE;