-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) TOTAL_SALES
from FOOD_PRODUCT p join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
where year(PRODUCE_DATE) = 2022 and  MONTH(o.PRODUCE_DATE) = 5
group by o.PRODUCT_ID
order by TOTAL_SALES desc, PRODUCT_ID