-- 코드를 입력하세요
SELECT B.WRITER_ID, U.NICKNAME, SUM(B.PRICE) AS SUM
FROM (
    SELECT * FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
     ) B LEFT JOIN USED_GOODS_USER U
 ON B.WRITER_ID = U.USER_ID
 GROUP BY WRITER_ID
 HAVING SUM >= 700000
 ORDER BY SUM;
 